### ISSUE TITLE
pushy0.15.0 Stream closed before a reply was received 

### ISSUE THREAD

**Issue by lijhua** [jchambers/pushy#1013]
”java.io.IOException: Stream closed before a reply was received “
This problem occurs frequently. Can I upgrade the pushy's version to solve this problem ?

**Comment by jchambers** [comment]
> Can I upgrade the pushy's version to solve this problem ?

No.

This problem generally indicates that you have an unsteady connection to the APNs server. Please note that users in China often report this problem. Apple does not have any APNs servers in China, and people frequently report poor connectivity to APNs servers from China.

Unfortunately, this is beyond Pushy's control.

Because I don't think there's anything we can do from this end to resolve the issue, I'm going to close this ticket for now. If you have reason to believe that something within Pushy is causing this problem, please leave a comment and I'll happily reopen this issue.
