### ISSUE TITLE
return success when send notifacation after uninstalling app

### ISSUE THREAD

**Issue by zcx-git1240** [jchambers/pushy#1029]
i sent message to a device which had no target app on it,because i uninstalling it,but pushy return me success,dose it has any error code tell me something is wrong, any reply thanks  very much.

**Comment by jchambers** [comment]
Apple makes no guarantees as to if or when they'll return an `Unregistered` response for an uninstalled destination. In practice, it seems like they've been introducing longer delays over the past several years to make it harder to learn when somebody has uninstalled an app, presumably as a privacy measure.

With that in mind, I don't think there's anything we can do within Pushy to address the situation because Pushy is accurately reporting the response it receives from the APNs server.
