### ISSUE TITLE
Wrong serialization of the object in JsonSerializer

### ISSUE THREAD

**Issue by idrabenia** [jchambers/pushy#1061]
Hi,

From our perspective it is generally wrong to call toString() for serialize objects to JSON. toString() is not defined to represent objects as JSON. 

https://github.com/jchambers/pushy/blob/e88d498cda07d4f1801ec02ef93723a965e40437/pushy/src/main/java/com/eatthepath/json/JsonSerializer.java#L678

**Comment by jchambers** [comment]
What do you think should happen instead?

**Comment by idrabenia** [comment]
If would be great to find all properties of the bean and serialize it also.

**Comment by jchambers** [comment]
Thank you for the suggestion, but I don't currently plan to make any change here.

The docs for [`ApnsPayloadBuilder#addCustomProperty`](https://pushy-apns.org/apidocs/0.15/com/eatthepath/pushy/apns/util/ApnsPayloadBuilder.html#addCustomProperty(java.lang.String,java.lang.Object)) call out that:

> The precise strategy for serializing the values of custom properties is defined by the specific ApnsPayloadBuilder implementation.

…and the default implementation (via [`JsonSerializer`](https://pushy-apns.org/apidocs/0.15/com/eatthepath/json/JsonSerializer.html)) calls out that (as you have noted/linked) that anything that doesn't map to a known type will be serialized as a string with the value of `obj.toString()`.

On top of that, as you've noted, we provide Jackson and Gson implementations that offer different behavior, and folks are free to use those as they see fit.

So, because:

1. Any change here would be a breaking change
2. The current behavior is documented
3. Alternatives are readily available

…I think it makes sense to leave the behavior as-is.
