### ISSUE TITLE
Token authentication channel with Stream Exception

### ISSUE THREAD

**Issue by Dawn1iu** [jchambers/pushy#758]
hello, when i use pushy 0.12.0 with Token authentication.
i got exceptions include 'Http2ChannelClosedException: Connection closed' and ' Stream closed before write could take place'.But at the same time some pushes are sccuessed.
so could you tell me that situation may cause this problem. thanks~

```
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:149)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:499)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:480)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105)
```

**Comment by jchambers** [comment]
Hi!

I'm afraid there's not enough information here for us to reasonably provide advice (I'd generally ask you to move the conversation to the mailing list for that kind of thing anyhow) or determine if there's a bug. I'm skeptical that there's a fundamental issue in Pushy because lots of people would be reporting the same issue if that were the case.

To help us figure out what's going wrong:

1. Can you tell us more about your setup? Do you have one client? Lots of clients? How many concurrent connections?
2. Are you located in China? We've historically seen very poor network performance because Apple doesn't have any APNs servers in China.
3. Is there anything else in the logs that might give us a hint about what's going wrong?

Also, could you please try with the latest version of Pushy? 0.12.0 is quite old at this point, and I'm wondering if the recent improvements could provide a clearer picture of what's going wrong (or just resolve the problem entirely).

Thanks!

**Comment by jchambers** [comment]
I'm going to close this ticket because we don't have enough information to investigate. @Dawn1iu if you have a chance to provide more information in the future, please do so and we'll happily reassess. Thanks!

**Comment by wrglive** [comment]
@Dawn1iu 你好, 这个问题您解决了吗

**Comment by Dawn1iu** [comment]
通过并发+限流控制优化了一下push这边连接情况，但没有整体复现出这个情况，怀疑还是和网络情况有关

**Comment by wrglive** [comment]
@Dawn1iu 我这边也限制了 单机qps的流量 到1500 但是还是会出现这个问题, 再等等作者怎么说吧....

**Comment by Dawn1iu** [comment]
> @Dawn1iu 我这边也限制了 单机qps的流量 到1500 但是还是会出现这个问题, 再等等作者怎么说吧....

作者已经关问题了，你开一个新的吧，我这边后来没复现出来就没再跟了
