### ISSUE TITLE
Using Pushy in ColdFusion 

### ISSUE THREAD

**Issue by magicBanana3** [jchambers/pushy#763]
Hello!

I'm trying to implement pushy in ColdFusion, therefore I try to convert the Java-sourcecode into the coldfusionlanguage.
Is there someone, who already use pushy in couldfusion and would share his code with me?

Otherwise, I have some attempts of code and someone could take a look at it, because I'm not sure, if I'm using the "createObject"-method in the right way.

I ask you for your help, because I don't have the possibility to test my code at the moment.

`<cfset ApnsClient = createObject( "java", "com.eatthepath.pushy.apns.ApnsClientBuilder" )
.setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST) .setClientCredentials(new File("/path/to/certificate.p12"), "MyCertPassword")
.build() />
`

`<cfset payload = createObject( "java", "com.eatthepath.pushy.apns.util.ApnsPayloadBuilder" ).setAlertBody("Example!") .buildWithDefaultMaximumLength()/>`

`<cfset pushNotification = createObject( "java", " com.eatthepath.pushy.apns.util.SimpleApnsPushNotification" ).init(token, "com.example.myApp", payload) />`

Thank you for your help! 
Have a nice day!

**Comment by jchambers** [comment]
Hi! I'm afraid that we don't really support ColdFusion in any official capacity right now. If you're looking for general help, the [mailing list](https://groups.google.com/d/forum/pushy-apns) may be the right place to go. To set expectations, though, I'm not aware of a significant ColdFusion user base for Pushy, and community expertise may be limited.

That said, I'm going to close this ticket for now because I don't believe there's any engineering change that needs to be made to Pushy to support this request; it's just a matter of gathering knowledge.

Good luck to you!
