### ISSUE TITLE
Occasionally, IOS  target device sometimes  receive notifation twice

### ISSUE THREAD

**Issue by qinjie2012** [jchambers/pushy#765]
Sometimes few devices received notifation twice, but cannot reproduce this scene. And the device show the same notifation received at the same delivered time. I use `pushy  0.13.8`,  and `new SimpleApnsPushNotification()` with params of `DeliveryPriority.IMMEDIATE, no null invalidationTime`. So, I want to know whether this parameter will cause repeated delivery? Thank U.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.

In the meantime, though:

> So, I want to know whether this parameter will cause repeated delivery?

There's no combination of parameters that should result in repeated delivery of notifications.
