### ISSUE TITLE
Pushy does not do ALPN

### ISSUE THREAD

**Issue by dmstocking** [jchambers/pushy#808]
I had to create my own mock APNS server and along the way discovered that Pushy does not do ALPN. This does not affect real requests to apple because apple seems to support just doing HTTP/2 without any negotiation. I was not lucky enough to be using a server that would work without ALPN. Specifically, I was using Ktor which fallsback to HTTP 1.1. The problem is that the `ApplicationProtocolConfig` is not provided. Netty has an [example](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2Client.java#L81) with the `ApplicationProtocolConfig` provided. I tested myself that if I recompiled Pushy and provided the same `ApplicationProtocolConfig` in the [ApnsClientBuilder](https://github.com/jchambers/pushy/blob/pushy-0.13.11/pushy/src/main/java/com/eatthepath/pushy/apns/ApnsClientBuilder.java#L535) that I do get ALPN to work. Is there some reason Pushy doesn't do ALPN? I didn't know if this was intentional or just missed because the apple servers support it. I also wasn't able to find if HTTP/2 technically requires ALPN. I couldn't find an RFC or anything saying it was mandatory. I can provide a PR if we want this changed. I think this should probably be fixed, but I don't know how everyone else feels.

**Comment by jchambers** [comment]
> Is there some reason Pushy doesn't do ALPN?

Yes; as you point out, it's not strictly required by the APNs servers and Java support for ALPN didn't appear until Java 9. Getting ALPN support in Java 8 requires using either `netty-tcnative` or `jetty-alpn-agent`. Pushy originally used ALPN, but we removed it because getting ALPN support for Java 8 was a major source of confusion.

It sounds like the main use case for adding ALPN back in would be to use Pushy with other mock servers; while I acknowledge that's a thing folks may want to do, it's not really a goal of the project.

While I sincerely appreciate the offer for a pull request, I think leaving ALPN out is the right thing to do for now. Thanks for the report!

**Comment by dmstocking** [comment]
Isn't that kind of risky? I don't know all server implementations but it appears that ALPN is pretty standard for HTTP/2. Would there be any harm in just setting it up and even if you don't negotiate h2 you still just do it anyway? I don't know if there  is any documentation on Apple's side that states this is a known and will not change. Considering how large Apple is, there could be a team creating the server library that isn't the APN team. It just seems like we are risking one day having all Pushy clients not work because ALPN wasn't required before.
