### ISSUE TITLE
push response always success

### ISSUE THREAD

**Issue by LeeHyunu** [jchambers/pushy#824]
when I tried this lib, send push works fine

However, I always received success response even after two week uninstalled app

how can I get uninstalled fail or unregistered token error?

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

That said, it sounds like Pushy is accurately reporting the response it receives from the server. Apple has changed this behavior many times over the years, and my understanding is that there's currently a long delay before a device will be reported as "unregistered."

I emphasize that we'd be happy to help, but let's move this conversation to a different venue.
