### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by damangueyu** [jchambers/pushy#834]
This error always comes up,but not every time，how do you think?
java.net.UnknownHostException: failed to resolve 'api.sandbox.push.apple.com' after 3 queries？

**Comment by damangueyu** [comment]
I found it worked on Windows but reported this error on Linux

**Comment by jchambers** [comment]
Sorry, friend; this sounds like a generic DNS problem, and is beyond Pushy's scope. I invite you to bring the question to the [Pushy mailing list](https://groups.google.com/d/forum/pushy-apns), but I'm going to close this issue because I don't think there's anything to fix within Pushy itself that would change this behavior.

**Comment by damangueyu** [comment]
Thank you,friend.
