### ISSUE TITLE
Always get 'DeviceTokenNotForTopic' in production mode

### ISSUE THREAD

**Issue by lanmaster** [jchambers/pushy#841]
Hello, i am getting this answer in my project, but in 'pushy-console' it works well. I use same certificate file, same machine for start applications, same token for device, same payload, same versions of 'pushy' connected with Maven (0.14.0) and same JDK (adopt-openjdk-11.0.9.1-1). I try to debug both projects (my and pushy-console) in Intellij Idea instances. And i cannot find where is my problem. Please help.

**Comment by MrThreepwood** [comment]
Generally when I've seen this it's because we are pushing to the wrong endpoint. If the device token was registered from a build created locally you need to send the push through the dev environment. I don't remember how that works with testflight, but essentially if an iOS build is in "sandbox" mode then it needs to be sent pushes using the dev APNS servers. 

I recommend whatever version you are using right now (dev vs. prod) switch to the other and see if it works.

**Comment by lanmaster** [comment]
There is production mode application. It connects to our server and send its device id. That device id we use when sending PUSH to production APNs server. It works from `pushy-console`, but didn't from our server app. By the way, we use `pushy` last version because trying to move our server app to the HTTP2 protocol from old binary. Old binary protocol supported with this library:
```
<groupId>com.relayrides</groupId>
<artifactId>pushy</artifactId>
<version>0.4.3</version>
```
Old library also in classpath exist. Can it broke `pushy` works?

**Comment by lanmaster** [comment]
I tried start with disabled old `pushy`, but nothing has changed. I saved traffic with `Wireshark` plus `jsslkeylog` from both applications. Only detected different is TLS 1.3 used on connection with my app, and TLS 1.2 used on `pushy-console`.


Also there is Apache HttpComponents included in classpath:
```
 <groupId>org.apache.httpcomponents</groupId>
 <artifactId>httpclient</artifactId>
 <version>4.5.4</version>
```
Can it broke `netty` ?

**Comment by lanmaster** [comment]
Sorry, i found problem on my side. It was a bug in code that connect created ApnsClient instances in one static variable. Closed.
