### ISSUE TITLE
apns push delay very high, sometimes got huge numbers of "Stream closed before a reply was received" error 

### ISSUE THREAD

**Issue by cyflhn** [jchambers/pushy#852]
Hi,
1. We found that the delay of apns push is very high. The delay sometimes is up to 30 minutes. 
2. We often got some errors like "Stream closed before a reply was received". Does it have something to do with the delay? What could be the cause of this error ?
3. We call apns service api from China. I am not sure whether these problems are caused by network problems.
So any suggestions for these issues?
Pushy version: 0.13.12
Thanks.

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. In the meantime, the problem is almost certainly that APNs users in China have historically had really bad network connectivity to Apple's servers. Apple doesn't have any APNs servers in China, and packet loss between China and Apple's servers tends to be quite high.

**Comment by hunshikan** [comment]
> Hi,
> 
> 1. We found that the delay of apns push is very high. The delay sometimes is up to 30 minutes.
> 2. We often got some errors like "Stream closed before a reply was received". Does it have something to do with the delay? What could be the cause of this error ?
> 3. We call apns service api from China. I am not sure whether these problems are caused by network problems.
>    So any suggestions for these issues?
>    Pushy version: 0.13.12
>    Thanks.

I have encountered the same problem as you. How can I find a good solution?

**Comment by cyflhn** [comment]
@hunshikan 
I can give you some pieces of advice.
1. retry when you get this error, you can get the result from the `future.get()`
2. try to use different network which is provided by other ISP.
3. try to deploy your own service in other regions if possible.
