### ISSUE TITLE
how to add https:// beofre api.sandbox.push.apple.com:443?

### ISSUE THREAD

**Issue by mikezang** [jchambers/pushy#859]
We use this project to push notification to iPhone app, but I got error by company proxy when request api.sandbox.push.apple.com:443, because our proxy forward it to http://api.sandbox.push.apple.com:443, I want to know how can we forward api.sandbox.push.apple.com:443 to https//api.sandbox.push.apple.com:443, but keep forward other.domain.com:80 still to http://other.domain.com:80?

**Comment by jchambers** [comment]
The `https` prefix in a URL tells whatever client is reading that URL that it should open a connection to the named domain on port 443 (unless otherwise specified) using the HTTPS (TLS) protocol. Pushy _always_ uses TLS and _always_ uses port 443 unless otherwise specified; there's no need for the protocol prefix. I'm not sure what your proxy is doing or how it's configured, but proxy configuration is outside of Pushy's control.

I realize this isn't a satisfying answer, but there's no action we can take on this end to help you; you'll need to work with your proxy administrator on this.
