### ISSUE TITLE
Push Notifications from Wildfly

### ISSUE THREAD

**Issue by GiordanoVicoli** [jchambers/pushy#987]
Hi,

Is anyone able to send push notifications from an application Server like wildfly?

Many thanks and regards,
Giordano

**Comment by jchambers** [comment]
@GiordanoVicoli This sounds like a request for general support rather than a bug report or a feature request. This isn't something we can resolve by making an engineering change to Pushy itself, and so this makes more sense as a [discussion](https://github.com/jchambers/pushy/discussions) rather than an [issue](https://github.com/jchambers/pushy/issues).

Normally, I would convert this issue to a discussion in the interest of continuity, but this is the third issue you have opened on what appears to be the same topic. Let's consolidate your question(s) in https://github.com/jchambers/pushy/discussions/984, the discussion we created for your first issue.

Please note that, if you want help, you need to provide some technical details about the problem you're having and answer questions from the people trying to help you. There are some open questions in https://github.com/jchambers/pushy/discussions/984; I recommend that you start by answering those to keep the discussion moving forward.
