### ISSUE TITLE
I send background notifications but app can not received

### ISSUE THREAD

**Issue by dagongren888** [jchambers/pushy#994]
hi, I want to ask a question. I developed as a server, send background notifications, but IOS App development colleagues said they had never received the message.
code likes :
```
SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(TokenUtil.sanitizeTokenString(token),
                topic, data, new Date(System.currentTimeMillis() + DEFAULT_EXPIRATION_PERIOD_MILLIS),
                DeliveryPriority.CONSERVE_POWER, PushType.BACKGROUND, null, null); 

PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                sendNotificationFuture = apnsClient.sendNotification(pushNotification);
```
use p8 cert. push type has set PushType.BACKGROUND and Priority set DeliveryPriority.CONSERVE_POWER.

version is 0.13.10
```
            <dependency>
                <groupId>com.turo</groupId>
                <artifactId>pushy</artifactId>
                <version>0.13.10</version>
            </dependency>
```

return is push success.But app can not recived messages.
Who can help me ? Be deeply grateful!

**Comment by jchambers** [comment]
In short: I don't know. Pushy's responsibilities extend up to the point of getting the notification to the APNs server, and it sounds like that's happening as expected. Whatever is going wrong is happening somewhere after that, and that's not something we can control from Pushy.

Because there doesn't appear to be any engineering change to make to Pushy itself, I'm going to close this issue. If you need general assistance, though, please feel free to [open a discussion](https://github.com/jchambers/pushy/discussions)!
